[tool.poetry]
name = "rascore"
version = "0.1.0"
description = "A package for analyzing the conformations of RAS structures"
authors = ["mitch-parker <mitch.isaac.parker@gmail.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.8"
Bio = "^1.3.2"
rdkit = "^2009.Q1-1"
pandas = "^1.2.4"
numpy = "^1.20.1"
scikit_learn = "^1.0.1"
statsmodels = "^0.12.2"
matplotlib = "^3.3.4"
seaborn = "^0.11.1"
tqdm = "^4.59.0"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
APPLICATION-NAME = 'rascore:main'
